language: python
python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"
 - "3.4_with_system_site_packages"

# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: "2.7_with_system_site_packages"
      dist: trusty
      env: DIST="trusty" PACKAGES="python-qt4 python-pyside python-gtk2 python-wxgtk2.8"
    - python: "2.7_with_system_site_packages"
      dist: xenial
      env: DIST="xenial" PACKAGES="python-qt4 python-pyside python-gtk2 python-wxgtk3.0"
    - python: 3.7
      dist: xenial
#      sudo: true

install:
 - sudo apt-get update -q
 - sudo apt-get install --no-install-recommends -y python-dev xvfb x11-utils x11-apps
 - sudo apt-get install --no-install-recommends -y scrot imagemagick 
 - sudo apt-get install --no-install-recommends -y $(echo $PACKAGES)
 - pip install -r requirements-test.txt
 - pip install .
 - pip install coveralls

script:  
 - xauth add :0 . `mcookie`
 - cd tests 
 - TESTS="easy test_scrot.py test_imagemagick.py"
 - if [ "$TRAVIS_PYTHON_VERSION" == "2.7_with_system_site_packages" ]; then TESTS="$TESTS test_pyside.py test_pyqt.py test_wx.py test_pygtk.py"; fi
 - nosetests -v --with-coverage --cover-package=pyscreenshot  $TESTS
  
after_success:
 - coveralls
